export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_AUTH = 'CLEAR_AUTH';
export const HIDE_TIMEOUT_WARNING = 'HIDE_TIMEOUT_WARNING';
export const SHOW_TIMEOUT_WARNING = 'SHOW_TIMEOUT_WARNING';
export const ONBOARDING_SUCCESS = 'ONBOARDING_SUCCESS';
export const UPDATE_SELECTED_VEHICLE_ID = 'ONBOARDING_SUCCESS';
export const UPDATING_USER_SUCCESS = 'UPDATING_USER_SUCCESS'

export const FETCH_FUEL_PURCHASE_DATA_SUCCESS = 'FETCH_FUEL_PURCHASE_DATA_SUCCESS';
export const FETCH_FUEL_PURCHASE_DATA_ERROR = 'FETCH_FUEL_PURCHASE_DATA_ERROR';
export const POST_FUEL_PURCHASE_DATA_SUCCESS = 'POST_FUEL_PURCHASE_DATA_SUCCESS';
export const POST_FUEL_PURCHASE_DATA_ERROR = 'POST_FUEL_PURCHASE_DATA_ERROR';

export const FETCH_VEHICLE_DATA_SUCCESS = 'FETCH_VEHICLE_DATA_SUCCESS';
export const FETCH_VEHICLE_DATA_ERROR = 'FETCH_VEHICLE_DATA_ERROR';
export const POST_VEHICLE_DATA_SUCCESS = 'POST_VEHICLE_DATA_SUCCESS';
export const POST_VEHICLE_DATA_ERROR = 'POST_VEHICLE_DATA_ERROR';
